### ISSUE TITLE
De-couple bands plugin from panels plugin

### ISSUE THREAD

**Issue by kitsuta** [magfest/bands#16]
If an event can turn off the ability to let bands apply for panels, that should also mean that the plugin itself is no longer dependent on the panels plugin

**Comment by EliAndrewC** [comment]
Interesting point.

In the long run, I expect the ``panels`` stuff to come into the main ``uber`` repo.  I don't think that should happen right away though, because in my mind there are two things that determines whether or not code makes it into the main plugin:

1) It should be sufficient generic to the point where we expect that practically every event might want it.  The ``panels`` stuff definitely qualifies here.

2) It should be sufficiently stable that we don't expect the models/API/webpages/functionality to radically change anytime soon.  The ``panels`` stuff fails this test because we really need to nuke it and rewrite large portions of it.

**Comment by kitsuta** [comment]
Yeah, I agree that a lot of the stuff in panels - if not most of its functionality, period - is core repo stuff. I get what you mean about it being in heavy development, though.
